apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LucasRius/lrios-argocd-appset.git
    targetRevision: HEAD
    path: monitoramento
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoramento
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
  